name: neurochurn
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.3
  - scikit-learn=1.2.2
  - tensorflow=2.12.0
  - matplotlib=3.7.1
  - pip
  - pip:
      - notebook
